sonar.organization=jonyrezende
sonar.projectKey=JonyRezende_finmanagement

sonar.sources=src/financas,server.py,scripts,public/js
sonar.python.coverage.reportPaths=coverage.xml
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=public/js/extrato.js,public/js/txnForm.js,public/js/main.js